### PR TITLE
Protobuf stubs update using mypy-protobuf

### LINKED ISSUE #2521: Incorrect types are used to describe google.protobuf enums
Let's take `google.protobuf.descriptor_pb2.FieldDescriptorProto` as an example.

In Python `FieldDescriptorProto.TYPE_DOUBLE` is instance of `int`
In mypy `FieldDescriptorProto.TYPE_DOUBLE` is instance of `FieldDescriptorProto.Type`

In Python `FieldDescriptorProto.Type` is instance of `EnumTypeWrapper`
In mypy `FieldDescriptorProto.Type` is subclass of `int` with additional methods

In Python `FieldDescriptorProto.Type.keys()` is of type `List[str]`
In mypy `FieldDescriptorProto.Type.keys()` is of type `List[bytes]`

In Python `EnumTypeWrapper.items` is an `instancemethod`
In mypy `EnumTypeWrapper.items` is a `classmethod`

In mypy this code works:
```python
from google.protobuf.descriptor_pb2 import FieldDescriptorProto
print(FieldDescriptorProto.TYPE_DOUBLE.values())
```
In Python it fails:
```python
Traceback (most recent call last):
  File "sandbox.py", line 5, in <module>
    print(FieldDescriptorProto.TYPE_DOUBLE.values())
AttributeError: 'int' object has no attribute 'values'
```
Currently this stub looks like this:
```python
class FieldDescriptorProto(Message):
    class Type(int):
        @classmethod
        def Name(cls, number: int) -> bytes: ...

        @classmethod
        def Value(cls, name: bytes) -> FieldDescriptorProto.Type: ...

        @classmethod
        def keys(cls) -> List[bytes]: ...

        @classmethod
        def values(cls) -> List[FieldDescriptorProto.Type]: ...

        @classmethod
        def items(cls) -> List[Tuple[bytes, FieldDescriptorProto.Type]]: ...
    TYPE_DOUBLE: Type
    ...
```
I think it is possible to change it into this:
```python
class FieldDescriptorProto(Message):
    FieldDescriptorProto_Type = typing.NewType('FieldDescriptorProto_Type', int)
    Type: EnumTypeWrapper[FieldDescriptorProto_Type]
    TYPE_DOUBLE: FieldDescriptorProto_Type
    ...
```
where `google.protobuf.internal.enum_type_wrapper.EnumTypeWrapper` looks like this:
```python
class EnumTypeWrapper(Generic[T]):
    def Name(self, number: T) -> str: ...
    def Value(self, name: str) -> T: ...
    def keys(self) -> List[str]: ...
    def values(self) -> List[T]: ...
    def items(self) -> List[Tuple[str, T]]: ...
```
The only problem I see is how to generate unique type name for enum values, in the example above I'm using concatenation of message name and enum name: `FieldDescriptorProto_Type`.

Is it ok to create PR with this fix?

### PR DESCRIPTION
**Pull request by nipunn1313**
This uses mypy-protobuf to check in up to date stubs for google.protobuf proto
files. The PR is split into two commits, one which checks in a script for generating
these stubs, and second for the generated .pyi stubs.

The current stubs were manually added from a very-old version of mypy-protobuf years ago (before mypy-protobuf was even open source). This PR updates them, and streamlines the process for updating them again in the future. With each release of protobuf, typeshed will have to update the stubs.

Fixes https://github.com/dropbox/mypy-protobuf/issues/158
Fixes #2521

Ultimately, much of this can be resolved by integrating mypy-protobuf with protobuf itself, but that's not currently on the horizon - tracked in both
https://github.com/dropbox/mypy-protobuf/issues/95
https://github.com/protocolbuffers/protobuf/issues/2638#issuecomment-495003625

### CODE REVIEW

**Comment by nipunn1313** [comment]
Sorry about all the force pushes! Took me a while to figure out how to skip black/isort/pytype/flake8 on these autogenerated files. This should be ready now!

File: scripts/generate_proto_stubs.sh [hunk 1]
```diff
@@ -0,0 +1,62 @@
+#!/bin/bash
```
Comment (JelleZijlstra) [inline scripts/generate_proto_stubs.sh:1]: Could you add a comment explaining the purpose of this file more directly?

Comment (nipunn1313) [reply scripts/generate_proto_stubs.sh:1]: yep! I elaborate on the comment - describing that the script autogenerates the _pb2.pyi files

Comment (JelleZijlstra) [reply scripts/generate_proto_stubs.sh:1]: Thanks, sounds good!

**Review by JelleZijlstra — APPROVED** [review]
This looks good to me but leaving it open for a little while in case @rchen152 wants to address the new pytype excludelist entries.

**Comment by rchen152** [comment]
Thanks for the ping! That's a lot of excludelist entries, so yeah, I think I'll want to fix the pytype parser. The Thanksgiving holiday is coming up, so I won't be able to release a fix until sometime next week at the earliest - feel free to merge this now, and I can clean up the pytype excludelist later.

**Comment by nipunn1313** [comment]
Thanks friends!
@rchen152 - it was the same error for all the excluded files - so hopefully it's not too difficult to fix!
